ZoeySite/Accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from . import views as accounts_views

app_name = 'Accounts'

urlpatterns = [
    # サインアップページ
    path('signup/', views.signup, name='signup'),
    # ログインページ
    path('login/', auth_views.LoginView.as_view(template_name="Accounts/login.html"), name='login'),
    # ログアウトページ
    path('logout/', auth_views.LogoutView.as_view(template_name="index.html"), name='logout'),
    # マイページ兼ユーザ情報閲覧ページ
    path('<int:pk>/', views.UserDetailView.as_view(), name="user_detail"),
    # ユーザ情報更新ページ
    path('<int:pk>/edit/', views.UserUpdateView.as_view(), name="user_update"),

    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='Accounts/password_reset.html',
        email_template_name='Accounts/password_reset_email.html',
        subject_template_name='Accounts/password_reset_subject.txt',
        success_url='done/'),
        name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='Accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='Accounts/password_reset_confirm.html',
        success_url=reverse_lazy('Accounts:password_reset_complete')),
        name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='Accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(
        template_name='Accounts/password_change.html',
        success_url=reverse_lazy('Accounts:password_change_done')),
        name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='Accounts/password_change_done.html'),
        name='password_change_done'),
]

ZoeySite/Board/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth import views as auth_views
from . import views as accounts_views

app_name = 'Board'

urlpatterns = [
    path('', TopicIndexView.as_view(), name='topic_index'),
    path('<str:game>/', TopicListView.as_view(), name='topic_list'),
    path('<str:game>/<uuid:pk>/', TopicDetailView.as_view(), name='topic_detail'),
    path('<str:game>/new/', TopicCreateView.as_view(), name='topic_create'),
    path('<str:game>/<uuid:pk>/post/', PostCreateView.as_view(), name='post_create')
]

ZoeySite/ZoeySite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('Accounts.urls')),
    path('board/', include('Board.urls')),
    path('match/', include('Matching.urls')),
    path('tournament/', include('Tournament.urls')),
    path('markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZoeySite/Accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

DEFAULT_IMAGE = "../../media/default/no_image.png"


class UserManager(BaseUserManager):

    # ユーザー新規作成時に呼び出されるメソッド
    def create_user(self, username, email, password=None):
        if not username:
            raise ValueError('Users must have an username')
        elif not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    # スーパーユーザー作成時に呼び出されるメソッド
    def create_superuser(self, username, email, password):
        user = self.create_user(
            username,
            email,
            password=password,
        )
        user.is_admin = True
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    psn_id = models.CharField(max_length=30)
    image = models.ImageField(upload_to='account_image', blank=True, null=True)
    image_thumbnail = ImageSpecField(source='image',
                                     processors=[ResizeToFill(50, 50)],
                                     format='JPEG',
                                     options={'quality': 60})
    status_enable = models.BooleanField(default=False)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return '<id:' + str(self.username) + ',' + str(self.email) + '>'

    def get_image(self):
        if not self.image:
            # depending on your template
            return DEFAULT_IMAGE
        else:
            return self.image.url

    def get_image_thumbnail(self):
        if not self.image_thumbnail:
            # depending on your template
            return DEFAULT_IMAGE
        else:
            return self.image_thumbnail.url

ZoeySite/Accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User

from django import forms

from django.contrib.auth import get_user_model
User = get_user_model()


# ユーザー登録用フォーム
# accounts/signup
class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = '＠ユーザー名'
        self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'
        self.fields['password2'].widget.attrs['placeholder'] = 'パスワード（確認）'


# ログインフォーム
class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'

        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'パスワード'

ZoeySite/Accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .forms import (
    LoginForm,
    SignUpForm,
)
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login

from django.utils.decorators import method_decorator
from django.views import generic

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
User = get_user_model()


# ユーザー登録ページ
def signup(request):
    # Submitボタンを押したら
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        # 入力内容に問題がなければ
        if form.is_valid():
            user = form.save()          # ユーザ情報保存
            auth_login(request, user)   # ログイン
            return redirect('index')    # リダイレクト
    else:
        form = SignUpForm()

    context = {
        'form': form,
    }
    return render(request, 'Accounts/signup.html', context)


# ログインページ
def login(request):
    context = {
        'template_name': 'login.html',
        'authentication_form': LoginForm
    }
    return auth_views.LoginView(request, **context)


# ログアウトページ
def logout(request):
    context = {
        'template_name': 'index.html',
    }
    return auth_views.LogoutView(request, **context)


@require_POST
def regist_save(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('users:index')

    context = {
        'form': form,
    }
    return render(request, 'signup.html', context)


class OnlyYouMixin(UserPassesTestMixin):
    """ユーザ情報更新ページは自分しかアクセス出来ないようにするMixin"""
    raise_exception = True

    # ログインユーザーのpkと、そのユーザー情報ページのpkが同じか、又はスーパーユーザーなら許可
    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetailView(generic.DetailView):
    """ユーザー情報閲覧ページ"""
    model = User
    template_name = 'Accounts/user_detail.html'


class UserUpdateView(OnlyYouMixin, generic.UpdateView):
    """ユーザー情報更新ページ。自分しかアクセス出来ない。"""
    model = User
    template_name = 'Accounts/user_update.html'
    success_url = reverse_lazy('Accounts:user_detail')
    fields = ("username", "email", "image", "psn_id")

    # TODO:formをhtmlに表示させる

ZoeySite/templates/Accounts/base_accounts.html
{% extends 'base_all.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'index' %}">Ezo</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

ZoeySite/templates/Accounts/login.html
{% extends 'base_all.html' %}

{% block title %}ログイン{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Ezoに登録していない <a href="{% url 'Accounts:signup' %}">サインアップ</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="#" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

ZoeySite/templates/Accounts/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

ZoeySite/templates/Accounts/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'index' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

ZoeySite/templates/Accounts/password_reset.html
{% extends 'Accounts/base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ZoeySite/templates/Accounts/password_reset_complete.html
{% extends 'Accounts/base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'Accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ZoeySite/templates/Accounts/password_reset_confirm.html
{% extends 'Accounts/base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'Accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ZoeySite/templates/Accounts/password_reset_done.html
{% extends 'Accounts/base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'Accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ZoeySite/templates/Accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'Accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The e-Social Team

ZoeySite/templates/Accounts/signup.html
{% extends 'Accounts/base_accounts.html' %}

{% block title %}Sign up to e-Social{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'Accounts:login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ZoeySite/templates/Accounts/user_detail.html
{% extends 'Accounts/base_accounts.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}

{% if user.pk == request.user.pk %}
<a href="{% url 'Accounts:user_update' user.pk %}">
	<button type="button" class="btn btn-primary btn-pill">Edit
		<i class="fas fa-user-edit"></i>
	</button>
</a>
{% endif %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <table class="table">
        <tbody>
        <tr>
          <th>ユーザー名</th>
          <td>{{ user.email }}</td>
        </tr>
        <tr>
          <th>姓</th>
          <td>{{ user.username }}</td>
        </tr>
        <tr>
          <th>名</th>
          <td>{{ user.psn_id }}</td>
        </tr>
        <tr>
          <th>画像</th>
          <td><img src= "{{ user.get_image }}"></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

ZoeySite/templates/Accounts/user_update.html
{% extends 'Accounts/base_accounts.html' %}

{% block title %}My account{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">My account</li>
{% endblock %}

{% block content %}

<div class="row">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <form method="post" novalidate>
      {% csrf_token %}
      {% include 'includes/form.html' %}
      <button type="submit" class="btn btn-success">Save changes</button>
    </form>
  </div>
</div>

{% endblock %}