ZoeySite/Accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from . import views as accounts_views

app_name = 'Accounts'

urlpatterns = [
    # サインアップページ
    path('signup/', views.signup, name='signup'),
    # ログインページ
    path('login/', auth_views.LoginView.as_view(template_name="Accounts/login.html"), name='login'),
    # ログアウトページ
    path('logout/', auth_views.LogoutView.as_view(template_name="index.html"), name='logout'),
    # マイページ兼ユーザ情報閲覧ページ
    path('<int:pk>/', views.UserDetailView.as_view(), name="user_detail"),
    # ユーザ情報更新ページ
    path('<int:pk>/edit/', views.UserUpdateView.as_view(), name="user_update"),

    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='Accounts/password_reset.html',
        email_template_name='Accounts/password_reset_email.html',
        subject_template_name='Accounts/password_reset_subject.txt',
        success_url='done/'),
        name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='Accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='Accounts/password_reset_confirm.html',
        success_url=reverse_lazy('Accounts:password_reset_complete')),
        name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='Accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(
        template_name='Accounts/password_change.html',
        success_url=reverse_lazy('Accounts:password_change_done')),
        name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='Accounts/password_change_done.html'),
        name='password_change_done'),
]

ZoeySite/Board/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth import views as auth_views
from . import views as accounts_views

app_name = 'Board'

urlpatterns = [
    path('', TopicIndexView.as_view(), name='topic_index'),
    path('<str:game>/', TopicListView.as_view(), name='topic_list'),
    path('<str:game>/<uuid:pk>/', TopicDetailView.as_view(), name='topic_detail'),
    path('<str:game>/new/', TopicCreateView.as_view(), name='topic_create'),
    path('<str:game>/<uuid:pk>/post/', PostCreateView.as_view(), name='post_create')
]

ZoeySite/Matching/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from .views import ActiveListView

app_name = 'Matching'

urlpatterns = [
    path('active/', ActiveListView.as_view(), name='active_list'),
]

ZoeySite/Tournament/urls.py
from django.urls import path, reverse_lazy
from .views import TournamentListView, TournamentDetailView, TournamentCreateView
app_name = 'Tournament'

urlpatterns = [
    path('', TournamentListView.as_view(), name='tournament_list'),
    path('<int:pk>/', TournamentDetailView.as_view(), name='tournament_detail'),
    path('create/', TournamentCreateView.as_view(), name='tournament_create'),
]

ZoeySite/ZoeySite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('Accounts.urls')),
    path('board/', include('Board.urls')),
    path('match/', include('Matching.urls')),
    path('tournament/', include('Tournament.urls')),
    path('markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZoeySite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}e-Social{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}  <!-- HERE -->
  </head>

  <body>
  {% block body %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}">e-Social</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="mainMenu">
              {% if user.is_authenticated %}
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                          <a class="dropdown-item" href="{% url 'Accounts:user_detail' %}">My account</a>
                          <a class="dropdown-item" href="{% url 'Accounts:password_change' %}">Change password</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'Accounts:logout' %}">Log out</a>
                      </div>
                  </li>
              </ul>

              {% else %}
              <form class="form-inline ml-auto">
                  <a href="{% url 'Accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
                  <a href="{% url 'Accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
              </form>
              {% endif %}
          </div>
      </div>
  </nav>

      {% block content %}
      {% endblock %}
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reboot.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet">
    <!-- js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  {% endblock body %}
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

ZoeySite/templates/base_all.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
	<title>{% block title %}Ezo{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
	<link rel="stylesheet" href="{% static 'css/my_style.css' %}">
	<link rel="stylesheet" href="{% static 'css/jpn.min.css' %}">

	{% block stylesheet %}{% endblock %}
</head>

<body>
<!--ヘッダー-->
<header id="header">
	<div class="container">
		<!--画面サイズmd(992-1119px)以上では横に羅列し、md未満ではトグル隠蔽化-->
		<nav class="navbar fixed-top navbar-expand-md no-gutters">
			<!--左：ブランド名-->
			<a class="navbar-brand" href="{% url 'index' %}">
				<img src="https://placehold.jp/600x150.png" height="30" alt="image">
			</a>
			<!--トグル-->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse-4"
			        aria-controls="navbarNav15" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<!--中央：メニュー一覧-->
			<div class="collapse navbar-collapse navbar-collapse-4 col-md-8" id="navbarNav15">
				<ul class="navbar-nav justify-content-center">
					<li class="nav-item active">
						<a class="nav-link fr-view" href="{% url 'Board:topic_index' %}"
						   style="outline: none; display: inline-block;">
							<i class="fas fa-pencil-alt fa-fw"></i>スレッド
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link fr-view" href="#"
						   style="outline: none; display: inline-block;">
							<i class="fas fa-users fa-fw"></i>クラン
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link fr-view" href="{% url 'Matching:active_list' %}"
						   style="outline: none; display: inline-block;">
							<i class="fas fa-handshake fa-fw"></i>パーティ
						</a>
					</li>
					<li class="nav-item">

						<a class="nav-link fr-view" href="{% url 'Tournament:tournament_list' %}"
						   style="outline: none; display: inline-block;">
							<i class="fas fa-crown fa-fw"></i>トーナメント
						</a>
					</li>
				</ul>
			</div>
			<!--右：User認証されている場合アカウント名、されていない場合ログイン-->
			<div class="collapse navbar-collapse navbar-collapse-4">
				<!--ユーザ認証済-->
				{% if user.is_authenticated %}
				<ul class="navbar-nav ml-auto">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
						   aria-haspopup="true" aria-expanded="false">
							<img class="image-thumbnail-30x30" src="{{ user.get_image }}" alt="image">
							{{ user.username }}
						</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
							<a class="dropdown-item" href="{% url 'Accounts:user_detail' user.pk %}">マイアカウント</a>
							<a class="dropdown-item" href="{% url 'Accounts:password_change' %}">パスワード変更</a>
							<a class="dropdown-item" href="{% url 'Accounts:logout' %}">ログアウト</a>
						</div>
					</li>
				</ul>
				<!--ユーザ未認証-->
				{% else %}
				<form class="form-inline ml-auto">
					<a href="{% url 'Accounts:login' %}" class="btn btn-outline-secondary login-btn">
						<i class="fas fa-sign-in-alt fa-fw"></i>ログイン</a>
				</form>
				{% endif %}
			</div>
		</nav>
	</div>
</header>
{% block body %}

{% block content %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>
{% block javascript %}{% endblock %}
{% endblock body %}
</body>
</html>

ZoeySite/templates/bootstrap_base.html
<!doctype html>
{% load static %}
<html lang="ja">
<head>
	<title>{% block title %}Ezo{% endblock %}</title>
	<!-- Meta -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
	<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p&display=swap&subset=japanese" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"-->
	      <!--integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
	      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap-honoka@4.3.1/dist/js/bootstrap.min.js"></script>
	{% block stylesheet %}{% endblock %}
</head>

<body>

{% block body %}

<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
	<div class="container">
		<a class="navbar-brand" href="{% url 'index' %}">e-Social</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
		        aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="mainMenu">
			{% if user.is_authenticated %}
			<ul class="navbar-nav ml-auto">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
					   aria-haspopup="true" aria-expanded="false">
						{{ user.username }}
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
						<a class="dropdown-item" href="{% url 'Accounts:user_detail' user.pk %}">My account</a>
						<a class="dropdown-item" href="{% url 'Accounts:password_change' %}">Change password</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'Accounts:logout' %}">Log out</a>
					</div>
				</li>
			</ul>

			{% else %}
			<form class="form-inline ml-auto">
				<a href="{% url 'Accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
				<a href="{% url 'Accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
			</form>
			{% endif %}
		</div>
	</div>
</nav>
{% block content %}{% endblock %}

<!-- JAVASCRIPTS (Load javascripts at bottom, this will reduce page load time) -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

{% endblock body %}
</body>
</html>

ZoeySite/templates/index.html
{% extends "base_all.html" %}
{% load static %}
{% block content %}

<!--サービス説明セクション-->
<section>
	<div class="jumbotron jumbotron-extend">
		<div class="container">
			<div class="row">
				<h1 class="neon">Welcome to Ezo!</h1>
			</div>
			<div class="row">
				<div class="card card-sin-up">
					<div class="card-body">
						<h6 class="card-title">アカウント作成</h6>
						<form method="post" novalidate>
							{% csrf_token %}
							{% include 'includes/form.html' %}
							<div class="button_wrapper">
							<button type="submit" class="btn btn-success" style="font-size:0.75em; width:80%;">アカウント作成</button>
							<button class="btn btn-primary" style="font-size:0.75em; width:80%; margin-top:1em;">
								<i class="fab fa-twitter"></i>
								Twitterでログイン</button>
							</div>
						</form>
					</div>
					<div class="card-footer text-muted text-center">
						<a href="{% url 'Accounts:login' %}"><h6>ログイン</h6></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}