ZoeySite/Accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from . import views as accounts_views

app_name = 'Accounts'

urlpatterns = [
    # サインアップページ
    path('signup/', views.signup, name='signup'),
    # ログインページ
    path('login/', auth_views.LoginView.as_view(template_name="Accounts/login.html"), name='login'),
    # ログアウトページ
    path('logout/', auth_views.LogoutView.as_view(template_name="index.html"), name='logout'),
    # マイページ兼ユーザ情報閲覧ページ
    path('<int:pk>/', views.UserDetailView.as_view(), name="user_detail"),
    # ユーザ情報更新ページ
    path('<int:pk>/edit/', views.UserUpdateView.as_view(), name="user_update"),

    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='Accounts/password_reset.html',
        email_template_name='Accounts/password_reset_email.html',
        subject_template_name='Accounts/password_reset_subject.txt',
        success_url='done/'),
        name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='Accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='Accounts/password_reset_confirm.html',
        success_url=reverse_lazy('Accounts:password_reset_complete')),
        name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='Accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(
        template_name='Accounts/password_change.html',
        success_url=reverse_lazy('Accounts:password_change_done')),
        name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='Accounts/password_change_done.html'),
        name='password_change_done'),
]

ZoeySite/Board/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth import views as auth_views
from . import views as accounts_views

app_name = 'Board'

urlpatterns = [
    path('', TopicIndexView.as_view(), name='topic_index'),
    path('<str:game>/', TopicListView.as_view(), name='topic_list'),
    path('<str:game>/<uuid:pk>/', TopicDetailView.as_view(), name='topic_detail'),
    path('<str:game>/new/', TopicCreateView.as_view(), name='topic_create'),
    path('<str:game>/<uuid:pk>/post/', PostCreateView.as_view(), name='post_create')
]

ZoeySite/Tournament/urls.py
from django.urls import path, reverse_lazy
from .views import TournamentListView, TournamentDetailView, TournamentCreateView
app_name = 'Tournament'

urlpatterns = [
    path('', TournamentListView.as_view(), name='tournament_list'),
    path('<int:pk>/', TournamentDetailView.as_view(), name='tournament_detail'),
    path('create/', TournamentCreateView.as_view(), name='tournament_create'),
]

ZoeySite/ZoeySite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('Accounts.urls')),
    path('board/', include('Board.urls')),
    path('match/', include('Matching.urls')),
    path('tournament/', include('Tournament.urls')),
    path('markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZoeySite/Tournament/models.py
from django.db import models
from django.conf import settings

GAME_CHOICES = [
    ('Fortnite', 'Fortnite'),
    ('ApexLegends', 'ApexLegends'),
    ('BO4', 'BO4'),
    ('BF5', 'BF5'),
    ('R6S', 'R6S'),
]


class BaseTournament(models.Model):
    """トーナメントクラス。開催者"""
    organizer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.CharField(max_length=500, null=False, blank=False)
    game = models.CharField(default='Fortnite', choices=GAME_CHOICES, max_length=20)
    holdTime = models.DateField(blank=True, null=True)
    deadTime = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True)
    limitParticipant = models.IntegerField(default=4)
    is_finish = models.BooleanField(default=False)

    class Mete:
        """abstract=Trueでマイグレーションされてもテーブルは作られない"""
        abstract = True


class IndividualTournament(BaseTournament):
    """個人参加の大会モデル"""
    participant = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)


# TODO:クラン管理アプリの作成後取り掛かる
# class ClanTournament(BaseTournament):
#     """クランが参加する大会モデル"""

ZoeySite/Tournament/forms.py
from django import forms
from .models import GAME_CHOICES, IndividualTournament

from bootstrap_datepicker_plus import DateTimePickerInput

GAME_CHOICES = GAME_CHOICES + [('', '---------')]


class IndividualTournamentSearchForm(forms.Form):
    game = forms.ChoiceField(label='ゲーム', choices=GAME_CHOICES, required=False)


class IndividualTournamentCreateForm(forms.ModelForm):

    class Meta:
        model = IndividualTournament
        fields = ['name', 'description', 'game', 'holdTime', 'deadTime', 'limitParticipant']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = '大会名'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['placeholder'] = '説明'
        self.fields['game'].widget.attrs['class'] = 'form-control'
        self.fields['game'].widget.attrs['placeholder'] = 'Fortnite'
        self.fields['holdTime'].widget.attrs['class'] = 'form-control'
        self.fields['holdTime'].widget = DateTimePickerInput(format='%Y-%m-%d',
                                                             options={'locale': 'ja',
                                                                      'dayViewHeaderFormat': 'YYYY年 MMMM',
                                                                      }
                                                             )

ZoeySite/Tournament/views.py
from django.shortcuts import render
from django.views import generic
from .models import IndividualTournament
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import IndividualTournamentSearchForm, IndividualTournamentCreateForm
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect


class TournamentListView(LoginRequiredMixin, generic.ListView):
    """トーナメントリストを表示するビュー。検索機能持ち"""
    template_name = "Tournament/tournament_list.html"
    paginate_by = 5
    model = IndividualTournament

    def post(self, request, *args, **kwargs):
        # HTMLからの入力を保持
        form_value = [
            self.request.POST.get('game', None),
        ]
        # 前回の検索条件をセッションに保存
        request.session['form_value'] = form_value
        # 検索時にページネーションに関連したエラーを防ぐ
        self.request.GET = self.request.GET.copy()
        self.request.GET.clear()
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # sessionに値がある場合、その値をセットする。（ページングしてもform値が変わらないように）
        game = ''
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            game = form_value[0]
        default_data = {'game': game, }
        search_form = IndividualTournamentSearchForm(initial=default_data)  # 検索フォーム
        context['search_form'] = search_form
        return context

    def get_queryset(self):
        # sessionに値がある場合、その値でクエリ発行する。
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            game = form_value[0]
            # 検索条件
            condition_game = Q()
            if len(game) != 0 and game[0]:
                condition_game = Q(game__icontains=game)
            return IndividualTournament.objects.select_related().filter(condition_game)
        else:
            # 何も返さない
            return IndividualTournament.objects.none()


class TournamentDetailView(LoginRequiredMixin, generic.DetailView):
    """トーナメントの詳細を表示するビュー"""

    template_name = "Tournament/tournament_detail.html"
    model = IndividualTournament
    context_object_name = "tournament"

    def post(self, request, *args, **kwargs):
        """POSTメソッドの際に呼び出される関数"""
        obj = self.get_object()
        # 参加済みならcancelアクションがHTMLから送られてくる
        if request.POST["user_action"] == "cancel":
            obj.participant.remove(request.user)
        else:
            obj.participant.add(request.user)
        return redirect('Tournament:tournament_list')

    def get_context_data(self, **kwargs):
        """HTMLファイルに変数を渡す関数。Get毎に呼ばれるっぽい"""
        context = super().get_context_data(**kwargs)
        return context


class TournamentCreateView(LoginRequiredMixin, generic.CreateView):
    """大会作成用ビュー"""
    model = IndividualTournament
    form_class = IndividualTournamentCreateForm
    template_name = "Tournament/tournament_create.html"
    success_url = "/"  # 成功時にリダイレクトするURL

    def form_valid(self, form):
        """フォームのバリデーションが通った時の処理"""
        obj = form.save(commit=False)
        obj.organizer = self.request.user
        obj.save()
        return super().form_valid(form)

ZoeySite/templates/Tournament/pagination.html
<nav aria-label="ページ送り">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ i }} <span class="sr-only">(現位置)</span></a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
        {% endif %}
    </ul>
</nav>

ZoeySite/templates/Tournament/tournament_create.html
{% extends "bootstrap_base.html" %}
{% block stylesheet %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

{% endblock %}
{% block content %}

    <form method="post">
    {% csrf_token %}

    {{ form }}
    <button type="submit">save</button>
    </form>

{% endblock %}

ZoeySite/templates/Tournament/tournament_detail.html
{% extends 'bootstrap_base.html' %}

{% block content %}

<body>
<h1>参加ユーザー一覧</h1>
<ul>
    {% for member in tournament.participant.all %}
	<li><a href="{% url 'Accounts:user_detail' member.pk %}">{{ member.username }}</a></li>
	{% endfor %}
</ul>

<form method="POST">
	{% csrf_token %}
	{% if user in tournament.participant.all %}
		<input type="hidden" name="user_action" value="cancel">
		<button type="submit" class="btn btn-primary">参加キャンセル</button>
	{% else %}
		<input type="hidden" name="user_action" value="part">
		<button type="submit" class="btn btn-primary">参加</button>
	{% endif %}

</form>

{% endblock %}

ZoeySite/templates/Tournament/tournament_list.html
{% extends 'base_all.html' %}
{% block content %}
	 <form method="POST">
        {% csrf_token %}
        {% for field in search_form %}
            <div class="form-group form-inline">
                <label class="col-md-offset-2 col-md-3 control-label">{{ field.label }}:</label>
                <div class="col-md-8">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <input class="btn btn-success offset-md-8 col-md-3" type="submit" id="button" name="button" value="検索">
    </form>

<h1>検索結果</h1>
    <section class="post-list">
        {% if object_list|length == 0 %}
            <p>検索結果が存在しません。</p>
        {% else %}
            <table class="table table-hover table-bordered">
                <tr>
                    <th>タイトル</th>
                    <th>内容</th>
                </tr>
                <tbody>
                {% for tournament in object_list %}
                    <tr>
	                    <td width="35%"><a href="{% url 'Tournament:tournament_detail' tournament.pk %}">{{ tournament.name }}</a></td>
                        <td width="65%">{{ tournament.description }}</td>
                        {% for member in tournament.participant.all %}
                            <td width="65%">{{ member }}</td>
	                    {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </section>
    <div class="col-6 offset-3 justify-content-center">
        {% if is_paginated %}
            {% include 'pagination.html' %}
        {% endif %}
    </div>
{% endblock %}