ZoeySite/Accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from . import views as accounts_views

app_name = 'Accounts'

urlpatterns = [
    # サインアップページ
    path('signup/', views.signup, name='signup'),
    # ログインページ
    path('login/', auth_views.LoginView.as_view(template_name="Accounts/login.html"), name='login'),
    # ログアウトページ
    path('logout/', auth_views.LogoutView.as_view(template_name="index.html"), name='logout'),
    # マイページ兼ユーザ情報閲覧ページ
    path('<int:pk>/', views.UserDetailView.as_view(), name="user_detail"),
    # ユーザ情報更新ページ
    path('<int:pk>/edit/', views.UserUpdateView.as_view(), name="user_update"),

    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='Accounts/password_reset.html',
        email_template_name='Accounts/password_reset_email.html',
        subject_template_name='Accounts/password_reset_subject.txt',
        success_url='done/'),
        name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='Accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='Accounts/password_reset_confirm.html',
        success_url=reverse_lazy('Accounts:password_reset_complete')),
        name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='Accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(
        template_name='Accounts/password_change.html',
        success_url=reverse_lazy('Accounts:password_change_done')),
        name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='Accounts/password_change_done.html'),
        name='password_change_done'),
]

ZoeySite/Board/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, reverse_lazy
from .views import *
from django.contrib.auth import views as auth_views
from . import views as accounts_views

app_name = 'Board'

urlpatterns = [
    path('', TopicIndexView.as_view(), name='topic_index'),
    path('<str:game>/', TopicListView.as_view(), name='topic_list'),
    path('<str:game>/<uuid:pk>/', TopicDetailView.as_view(), name='topic_detail'),
    path('<str:game>/new/', TopicCreateView.as_view(), name='topic_create'),
    path('<str:game>/<uuid:pk>/post/', PostCreateView.as_view(), name='post_create')
]

ZoeySite/ZoeySite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('Accounts.urls')),
    path('board/', include('Board.urls')),
    path('match/', include('Matching.urls')),
    path('tournament/', include('Tournament.urls')),
    path('markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ZoeySite/Board/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from django.conf import settings
import uuid
from django.contrib.humanize.templatetags.humanize import naturaltime
import re
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from .consts import GAME_LIST
from django.utils import timezone

pattern = r"([\,]+),*(.*)"
repeater = re.compile(pattern)

DEFAULT_IMAGE = "../../media/default/no_image.png"

class Game(models.Model):
    title = models.CharField(max_length=32, choices=GAME_LIST, null=True)
    def __str__(self):
        return "{0}".format(self.title)

    def get_game_image(self):
        return "url(../game/{0}.png);".format(self.title)


class Tag(models.Model):
    """
    This model associate with Topic.
    User can create and select tag when create Topic.
    """
    tag = models.CharField(max_length=32)

    def __str__(self):
        return "{0}".format(self.tag)


class Topic(models.Model):
    """
    This model is main-contents in Board.
    User create a topic and be reply fro any Users.
    Automatically be added views, reply-count and update-time.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    contents = MarkdownxField('Contents')
    last_updated = models.DateTimeField(default=timezone.now)
    starter = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_topics', on_delete=models.SET_NULL, null=True)
    views = models.PositiveIntegerField(default=0)
    game = models.ForeignKey(Game, related_name="game_topics", on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    image = models.ImageField(upload_to='topic_images', blank=True, null=True)

    objects = models.Manager()

    def __str__(self):
        return "{0},{1}".format(self.game, self.last_updated, )

    def get_image(self):
        if not self.image:
            return DEFAULT_IMAGE
        else:
            return self.image.url

    def get_reply_count(self):
        return self.posts.count()

    def get_tags(self):
        return self.tags.all()


class Post(models.Model):
    """
    This models is reply to a Topic.
    """
    message = models.TextField(max_length=1024)
    topic = models.ForeignKey(Topic, related_name='posts', on_delete=models.CASCADE)
    posted_at = models.DateTimeField(auto_now_add=True)
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts', on_delete=models.SET_NULL, null=True)

    objects = models.Manager()

    def __str__(self):
        return "{0},{1},{2}".format(self.topic, self.posted_by, self.message)

ZoeySite/Board/forms.py
from django import forms
from .models import Topic, Post, Tag
from .consts import *
from django.utils.encoding import force_text
from .widgets import FileInputWithPreview



class TopicForm(forms.ModelForm):
    # text_tag = forms.CharField(max_length=160, required=False, label='タグ：')

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        label='タグ',
        required=False,
        widget=forms.CheckboxSelectMultiple())

    image = forms.ImageField(widget=FileInputWithPreview(include_preview=False), required=False)

    class Meta:
        model = Topic
        fields = ('contents', 'image', 'tags')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 画像投稿<input>を装飾するため
        self.fields['image'].widget.attrs['style'] = "display:none"
        # self.fields['text_tag'].widget.attrs['placeholder'] = 'スペース区切り'
        # self.fields['text_tag'].widget.attrs['class'] = 'text-tag'

    # def save(self, commit=True):
    #     """
    #     saveメソッドのオーバーライド
    #     m2mフィールドを追加・作成するため
    #     """
    #     # まず保存
    #     instance = super(TopicForm, self).save()
    #     # POSTから受け取ったtext_tagを空白で区切り、既に存在するTagならadd,新規タグならcreate
    #     split_tags = self.cleaned_data['text_tag'].split()
    #     for t in split_tags:
    #         if Tag.objects.filter(tag=t):
    #             tmp = Tag.objects.get(tag=t)
    #             instance.tags.add(tmp)
    #         else:
    #             instance.tags.create(tag=t)
    #     return instance


class TopicSearchForm(forms.Form):
    """
        topic_list.htmlにて、クエリセットを絞り込み・並び替えするためのフォーム
    """
    game = forms.ChoiceField(label='ゲーム', choices=GAME_LIST, required=False,
                             widget=forms.Select(attrs={"onChange": 'this.form.submit()'}))
    date = forms.ChoiceField(label='日付', choices=DATE_LIST, required=False,
                             widget=forms.Select(attrs={"onChange": 'this.form.submit()'}))
    order = forms.ChoiceField(label='並び', choices=ORDER_LIST, required=False,
                              widget=forms.Select(attrs={"onChange": 'this.form.submit()'}))


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']

ZoeySite/Board/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import *
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib.auth import get_user_model
from .forms import TopicForm, PostForm, TopicSearchForm
from django.views import generic
from django.views.generic.edit import ModelFormMixin, ProcessFormView, FormMixin
from django.urls import reverse
from django.db.models import Q
from .consts import *


class TopicIndexView(generic.ListView):
    model = Game
    context_object_name = "game_list"
    template_name = "Board/topic_index.html"


class TopicListView(ProcessFormView, generic.ListView):
    """トピック一覧を表示するビュー"""
    model = Topic  # モデル指定
    paginate_by = 10  # 一ページに出力する件数指定
    context_object_name = "topic_list"  # html内でtopic_listという名前で使えるようにする
    template_name = "Board/topic_list.html"

    def get(self, request, *args, **kwargs):
        """GETメソッド時呼び出し関数"""
        # request.session.clear()
        self.object = None
        self.object_list = self.get_queryset()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """
            POSTメソッド時呼び出し関数（検索条件入力時）
            役割：セッションに検索条件を渡す
        """
        # HTMLからの入力保持
        form_value = [
            # self.request.POST.get('game', None),
            self.request.POST.get('date', None),
            self.request.POST.get('order', None),
        ]
        # 検索条件をセッションに保存
        request.session['form_value'] = form_value
        # 検索時にページネーションに関連したエラーを防ぐ
        self.request.GET = self.request.GET.copy()
        self.request.GET.clear()
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
            役割：セッションを読み、検索条件の初期値を設定する
        """
        context = super().get_context_data(**kwargs)
        # game = ''
        date = ''
        order = ''
        # sessionに値がある:既存値をセット（ページングしてもform値変えない）
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            # game = form_value[0]
            date = form_value[0]
            order = form_value[1]
        default_data = {'date': date, 'order': order}
        search_form = TopicSearchForm(initial=default_data)
        context['search_form'] = search_form
        context['game'] = self.kwargs['game']
        return context

    def get_queryset(self):
        """
            役割：セッションの検索条件に応じたクエリセットを発行する
        """
        # sessionに値がある場合、その値でクエリ発行する。
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            # game = form_value[0]
            game = self.kwargs['game']
            date = form_value[0]
            order = form_value[1]
            end, start = get_date_range(date)
            print(start, end)
            # 検索条件
            return Topic.objects.select_related().filter(game__title=game,
                                                         last_updated__range=[start, end]).order_by(order)
        else:
            # 何も返さない
            return Topic.objects.none()


class TopicDetailView(generic.DetailView):
    """トピックの詳細を表示するビュー"""
    template_name = "Board/topic_detail.html"
    model = Topic
    context_object_name = "topic_instance"

    def get_context_data(self, **kwargs):
        """HTMLファイルに変数を渡す関数。Get毎に呼ばれるっぽい"""
        # 同じユーザでview数を増やさない処理
        session_key = 'viewed_topic_{}'.format(self.object.pk)
        if not self.request.session.get(session_key, False):
            self.object.views += 1
            self.object.save()
            self.request.session[session_key] = True
        # Postリストを取得
        post_list = Post.objects.filter(topic=self.object)
        # Tagリストを取得
        tag_list = Tag.objects.filter(topic=self.object)
        kwargs['post_list'] = post_list
        kwargs['tag_list'] = tag_list
        kwargs['game'] = self.kwargs['game']
        return super().get_context_data(**kwargs)


class TopicCreateView(generic.CreateView):
    """新しくトピックを作成するview"""
    template_name = "Board/topic_create.html"
    model = Topic
    form_class = TopicForm
    success_url = "/board"

    def form_valid(self, form):
        # saveはせず、モデルを受け取る
        update = form.save(commit=False)
        # starterを設定
        update.starter = self.request.user
        update.game = Game.objects.get(title=self.kwargs['game'])
        # saveする
        update.save()
        form.save_m2m()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)


class PostCreateView(generic.CreateView):
    """新しくPostを投稿するview"""
    template_name = "Board/post_create.html"
    model = Post
    form_class = PostForm

    # Post投稿後は、投稿先Topicページへ遷移
    def get_success_url(self):
        return reverse('Board:topic_detail', kwargs={'pk': self.object.topic.id})

    # 親topicとpostユーザを格納して保存
    def form_valid(self, form):
        form.instance.topic = Topic.objects.get(id=self.kwargs['pk'])
        form.instance.posted_by = self.request.user
        return super().form_valid(form)

ZoeySite/templates/Board/board_index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Board</title>
  </head>
  <body>
    <h1>Board</h1>

    <table border="1">
      <thead>
        <tr>
          <th>Board</th>
          <th>Posts</th>
          <th>Last Post</th>
        </tr>
      </thead>
      <tbody>
        {% for board in boards %}
          <tr>
            <td>
              {{ board.name }}<br>
              <small style="color: #888">{{ board.description }}</small>
            </td>
            <td>0</td>
            <td>0</td>
            <td></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

ZoeySite/templates/Board/contents.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ board.name }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    <div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'Board:home' %}">Boards</a></li>
        <li class="breadcrumb-item active">{{ board.name }}</li>
      </ol>
    </div>
  </body>
</html>

ZoeySite/templates/Board/home.html
{% extends 'base_all.html' %}
{% block content %}
    <div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active">Boards</li>
      </ol>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>

        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                <a href="{% url 'Board:topic_list' board.id%}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">0</td>
              <td class="align-middle">0</td>
              <td></td>
            </tr>
          {% endfor %}
        </tbody>

      </table>
    </div>
{% endblock %}

ZoeySite/templates/Board/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'Board:home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'Board:topic_list' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
      <!-- postメソッドにおいてcsrfトークンは必須
    {% csrf_token %}
      <!-- form.as_pでhtml表記に変換する -->
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

ZoeySite/templates/Board/post_create.html
{% extends 'base_all.html' %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

ZoeySite/templates/Board/topic_create.html
{% extends 'base_all.html' %}
{% block title %}Start a New Topic{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
<script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
{% endblock %}

{% block content %}
<div class="container mt-2">
    <form method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="field">
            {{ form.contents }}
            <span class="helptext">{{ form.contents.help_text }}</span>
            {{ form.contents.errors }}
        </div>
        <!-- 切り替えボタンの設定 data-targetをusernameでネーミングしておかないとモーダル毎でUserを分けれない -->
        <div class="btn-wrapper my-1">
            <button class="btn btn-dot" type="button" data-toggle="modal" data-target="#select-tag">
                <i class="fas fa-tags"></i>タグを選択
            </button>
        </div>

        <div class="btn-wrapper field my-1">
            <label class="btn btn-dot">
                <i class="fas fa-image"></i>画像を挿入{{ form.image }}
            </label>
            <span class="helptext">{{ form.image.help_text }}</span>
            {{ form.image.errors }}
        </div>
        {{ form.media }}

        <div class="field">
            <button type="submit" class="btn btn-success w-100">投稿</button>
        </div>

    </form>

    <img id="image-preview">


    <!-- モーダル -->
    <div class="field mt-3">
        <div class="modal fade" id="select-tag" tabindex="-1" role="dialog" aria-labelledby="label1"
             aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="label1">タグを選択</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="tag-wrapper" role="group" data-toggle="buttons">
                            {% for checkbox in form.tags %}
                            <label class="btn btn-primary w-40">
                                {{ checkbox.tag }} {{ checkbox.choice_label }}
                            </label>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}
</div>

{% block javascript %}
<script>
    var easyMDE = new EasyMDE({
    autoDownloadFontAwesome: false,
    autosave: {
		enabled: true,
		uniqueId: "MyUniqueID",
		delay: 1000,
	},
	status: false,
    toolbar: [
        "preview",
        {
            name: "bold",
            action: EasyMDE.toggleBold,
            className: "fas fa-bold",
            title: "太字",
        },{
            name: "italic",
            action: EasyMDE.toggleItalic,
            className: "fas fa-italic",
            title: "斜字",
        },{
            name: "heading",
            action: EasyMDE.toggleHeadingSmaller,
            className: "fas fa-heading",
            title: "見出し",
        },{
            name: "strikethrough",
            action: EasyMDE.toggleStrikethrough,
            className: "fas fa-strikethrough",
            title: "取り消し線",
        },{
            name: "quote",
            action: EasyMDE.toggleBlockquote,
            className: "fas fa-quote-left",
            title: "引用",
        },{
            name: "unordered-list",
            action: EasyMDE.toggleUnorderedList,
            className: "fas fa-list-ul",
            title: "リスト",
        },{
            name: "ordered-list",
            action: EasyMDE.toggleOrderedList,
            className: "fas fa-list-ol",
            title: "番号リスト",
        },{
            name: "table",
            action: EasyMDE.drawTable,
            className: "fas fa-table",
            title: "表",
        },{
            name: "link",
            action: EasyMDE.drawLink,
            className: "fas fa-link",
            title: "リンク",
        }
    ],
});


</script>
{% endblock %}

ZoeySite/templates/Board/topic_detail.html
{% extends 'base_all.html' %}
{% load humanize %}
{% load board_templatetags %}
{% block content %}

<div class="my-fixed-bottom">
    <a href="{% url 'Board:post_create' game.title topic_instance.id %}" id="fab"><span><i class="fas fa-reply"></i></span></a>
</div>

<div class="container mt-2">
    <div class="card">
        <div class="card-body">
            <div class="card-title mb-0">
                <h5 class="mb-0">
                    <img class="image-thumbnail" id="starter" src="{{ topic_instance.starter.get_image }}" alt="image">
                    {{ topic_instance.starter.username }}
                    <small class="text-muted ml-3">
                        <i class="fas fa-clock"></i>{{ topic_instance.last_updated }}
                    </small>
                </h5>

            </div>
            <div class="tag">{{ topic_instance.game }}</div>
            {% for tag in tag_list %}
                <div class="tag">{{ tag }}</div>
            {% endfor %}
            <p class="card-text my-1">{{ topic_instance.contents | markdown_to_html }}</p>
        </div>
        <img class="card-img-bottom" src="{{ topic_instance.get_image }}" alt="カードの画像">
        <div class="card-footer">
            <p class="card-text">
                <small class="text-muted">
                    <i class="fas fa-eye"></i>{{ topic_instance.views }}
                    <i class="fas fa-comment-dots"></i>{{ topic_instance.get_reply_count }}
                    <i class="fas fa-share-alt"></i>Share
                </small>
            </p>
        </div>
    </div>

    {% for post in post_list %}
    <div class="card post my-2">
        <div class="card-body">
            <div class="card-title mb-0">
                <a href="{% url 'Accounts:user_detail' user.pk %}">
                    <img src="{{ post.posted_by.get_image }}" alt="image">
                    {{ post.posted_by.username }}

                </a>
                <small class="text-muted ml-2">{{ post.posted_at }}</small>
            </div>
            <p class="mx-3">{{ post.message }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

ZoeySite/templates/Board/topic_index.html
{% extends 'base_all.html' %}
{% load humanize %}
{% block content %}
<div class="container">
    {% for game in game_list %}
        <a href="{% url 'Board:topic_list' game.title %}">{{ game.title }}</a>
    {% endfor %}
</div>
{% endblock %}

ZoeySite/templates/Board/topic_list.html
{% extends 'base_all.html' %}
{% load humanize %}
{% load board_templatetags %}
{% block content %}

<div class="my-fixed-bottom">
    <a href="{% url 'Board:topic_create' game.title %}" id="fab"><span><i class="fas fa-pencil-alt"></i></span></a>
</div>

<div class="container main-bg">
    <div class="row">
        <div class="col-12" id="{{ game.title }}"></div>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="row mb-2">
            <div class="col-4 px-2 align-self-center">
                <div class="selectdiv">
                    {{ search_form.order }}
                </div>
            </div>
            <div class="col-3 px-2 align-self-center">
                <div class="selectdiv">
                    {{ search_form.date }}
                </div>
            </div>
        </div>
    </form>

    {% for topic in topic_list %}
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-3 col-md-4">
                <a href="{% url 'Board:topic_detail' game.title topic.id%}">
                    <img class="topic_image_thumbnail" src="{{ topic.get_image }}" alt="image">
                </a>
            </div>
            <div class="col-9 col-md-8">
                <div class="card-header">
                    <div class="card-text"><small class="text-muted">
                        <i class="fas fa-eye"></i>{{ topic.views }}
                        <i class="fas fa-comment-dots"></i>{{ topic.get_reply_count }}
                        <i class="fas fa-clock"></i>{{ topic.last_updated|naturaltime }}
                    </small>
                    </div>
                </div>
                <div class="card-body">
                    <div class="topic-list-userinfo">
                        <span class="card-text mr-2">
                            <img class="image-thumbnail" src="{{ topic.starter.get_image }}"
                                 alt="image">
                            {{ topic.starter.username }}
                        </span>
                        <span class="tag">{{topic.game}}</span>
                        {% for tag in topic.get_tags %}
                        <span class="tag">{{tag}}</span>
                        {% endfor %}
                    </div>
                    <p class="card-text topic-list-body mt-1">
                        <a href="{% url 'Board:topic_detail' game.title topic.id%}">
                            {{ topic.contents|remove_html_tags|truncatechars:40}}</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}